declare const childProcess: any;
declare const chokidar: any;
declare const path: any;
declare const PROJECT_DIR: any;
declare const SRC_DIRNAME = "src";
declare const SRC_DIR: any;
declare const DEST_PROJECT_REL_PATH: string;
declare const HYPERVIEW_DIR: any;
declare const HYPERVIEW_SRC_DIR: any;
declare const updatePackageJson: () => void;
declare const syncFiles: (event: any, originPath: any) => void;
