// flow-typed signature: 0da42644136fde61e1e9f61f704fdc7e
// flow-typed version: <<STUB>>/react-native-keyboard-aware-scroll-view_v0.4.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keyboard-aware-scroll-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keyboard-aware-scroll-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareFlatList' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareInterface' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareListView' {
  declare module.exports: any;
}

declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareScrollView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-keyboard-aware-scroll-view/index' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view'>;
}
declare module 'react-native-keyboard-aware-scroll-view/index.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view'>;
}
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareFlatList.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareFlatList'>;
}
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC'>;
}
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareInterface.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareInterface'>;
}
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareListView.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareListView'>;
}
declare module 'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareScrollView.js' {
  declare module.exports: $Exports<'react-native-keyboard-aware-scroll-view/lib/KeyboardAwareScrollView'>;
}
