// flow-typed signature: d9b262b585c75b2e8d57a7e006272736
// flow-typed version: <<STUB>>/react-navigation_v1.0.0-beta.11/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-navigation/lib-rn/addNavigationHelpers' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/createNavigationContainer' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/NavigationActions' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/navigators/createNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/navigators/DrawerNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/navigators/NavigatorTypes' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/navigators/StackNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/navigators/TabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/PlatformHelpers' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/PlatformHelpers.native' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/react-navigation' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/react-navigation.web' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/routers/createConfigGetter' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/routers/getScreenConfigDeprecated' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/routers/getScreenForRouteName' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/routers/StackRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/routers/TabRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/routers/validateRouteConfigMap' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/routers/validateScreenOptions' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/StateUtils' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/TypeDefinition' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/AnimatedValueSubscription' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/Card' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/CardStack' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/CardStackStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/CardStackTransitioner' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/Drawer/DrawerNavigatorItems' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/Drawer/DrawerScreen' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/Drawer/DrawerSidebar' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/Drawer/DrawerView' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/Header' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/HeaderBackButton' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/HeaderStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/HeaderTitle' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/PointerEventsContainer' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/ScenesReducer' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/SceneView' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/TabView/TabBarBottom' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/TabView/TabBarIcon' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/TabView/TabBarTop' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/TabView/TabView' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/TouchableItem' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/TransitionConfigs' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/Transitioner' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/views/withNavigation' {
  declare module.exports: any;
}

declare module 'react-navigation/lib-rn/withCachedChildNavigation' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/addNavigationHelpers' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/createNavigationContainer' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/NavigationActions' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/navigators/createNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/navigators/DrawerNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/navigators/NavigatorTypes' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/navigators/StackNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/navigators/TabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/PlatformHelpers' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/PlatformHelpers.native' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/react-navigation' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/react-navigation.web' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/routers/createConfigGetter' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/routers/getScreenConfigDeprecated' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/routers/getScreenForRouteName' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/routers/StackRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/routers/TabRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/routers/validateRouteConfigMap' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/routers/validateScreenOptions' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/StateUtils' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/TypeDefinition' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/AnimatedValueSubscription' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/Card' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/CardStack' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/CardStackStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/CardStackTransitioner' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/Drawer/DrawerNavigatorItems' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/Drawer/DrawerScreen' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/Drawer/DrawerSidebar' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/Drawer/DrawerView' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/Header' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/HeaderBackButton' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/HeaderStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/HeaderTitle' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/PointerEventsContainer' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/ScenesReducer' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/SceneView' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/TabView/TabBarBottom' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/TabView/TabBarIcon' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/TabView/TabBarTop' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/TabView/TabView' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/TouchableItem' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/TransitionConfigs' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/Transitioner' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/views/withNavigation' {
  declare module.exports: any;
}

declare module 'react-navigation/lib/withCachedChildNavigation' {
  declare module.exports: any;
}

declare module 'react-navigation/src/__tests__/addNavigationHelpers-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/__tests__/NavigationActions-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/__tests__/NavigationStateUtils-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/addNavigationHelpers' {
  declare module.exports: any;
}

declare module 'react-navigation/src/createNavigationContainer' {
  declare module.exports: any;
}

declare module 'react-navigation/src/NavigationActions' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/createNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/DrawerNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/NavigatorTypes' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/StackNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/navigators/TabNavigator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/PlatformHelpers' {
  declare module.exports: any;
}

declare module 'react-navigation/src/PlatformHelpers.native' {
  declare module.exports: any;
}

declare module 'react-navigation/src/react-navigation' {
  declare module.exports: any;
}

declare module 'react-navigation/src/react-navigation.web' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/createConfigGetter-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/Routers-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/StackRouter-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/TabRouter-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/__tests__/validateRouteConfigMap-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/createConfigGetter' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/getScreenConfigDeprecated' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/getScreenForRouteName' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/StackRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/TabRouter' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/validateRouteConfigMap' {
  declare module.exports: any;
}

declare module 'react-navigation/src/routers/validateScreenOptions' {
  declare module.exports: any;
}

declare module 'react-navigation/src/StateUtils' {
  declare module.exports: any;
}

declare module 'react-navigation/src/TypeDefinition' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/__tests__/NavigationScenesReducer-test' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/AnimatedValueSubscription' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Card' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/CardStack' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/CardStackStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/CardStackTransitioner' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Drawer/DrawerNavigatorItems' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Drawer/DrawerScreen' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Drawer/DrawerSidebar' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Drawer/DrawerView' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Header' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/HeaderBackButton' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/HeaderStyleInterpolator' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/HeaderTitle' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/PointerEventsContainer' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/ScenesReducer' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/SceneView' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/TabView/TabBarBottom' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/TabView/TabBarIcon' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/TabView/TabBarTop' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/TabView/TabView' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/TouchableItem' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/TransitionConfigs' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/Transitioner' {
  declare module.exports: any;
}

declare module 'react-navigation/src/views/withNavigation' {
  declare module.exports: any;
}

declare module 'react-navigation/src/withCachedChildNavigation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-navigation/lib-rn/addNavigationHelpers.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/addNavigationHelpers'>;
}
declare module 'react-navigation/lib-rn/createNavigationContainer.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/createNavigationContainer'>;
}
declare module 'react-navigation/lib-rn/NavigationActions.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/NavigationActions'>;
}
declare module 'react-navigation/lib-rn/navigators/createNavigator.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/navigators/createNavigator'>;
}
declare module 'react-navigation/lib-rn/navigators/DrawerNavigator.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/navigators/DrawerNavigator'>;
}
declare module 'react-navigation/lib-rn/navigators/NavigatorTypes.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/navigators/NavigatorTypes'>;
}
declare module 'react-navigation/lib-rn/navigators/StackNavigator.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/navigators/StackNavigator'>;
}
declare module 'react-navigation/lib-rn/navigators/TabNavigator.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/navigators/TabNavigator'>;
}
declare module 'react-navigation/lib-rn/PlatformHelpers.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/PlatformHelpers'>;
}
declare module 'react-navigation/lib-rn/PlatformHelpers.native.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/PlatformHelpers.native'>;
}
declare module 'react-navigation/lib-rn/react-navigation.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/react-navigation'>;
}
declare module 'react-navigation/lib-rn/react-navigation.web.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/react-navigation.web'>;
}
declare module 'react-navigation/lib-rn/routers/createConfigGetter.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/routers/createConfigGetter'>;
}
declare module 'react-navigation/lib-rn/routers/getScreenConfigDeprecated.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/routers/getScreenConfigDeprecated'>;
}
declare module 'react-navigation/lib-rn/routers/getScreenForRouteName.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/routers/getScreenForRouteName'>;
}
declare module 'react-navigation/lib-rn/routers/StackRouter.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/routers/StackRouter'>;
}
declare module 'react-navigation/lib-rn/routers/TabRouter.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/routers/TabRouter'>;
}
declare module 'react-navigation/lib-rn/routers/validateRouteConfigMap.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/routers/validateRouteConfigMap'>;
}
declare module 'react-navigation/lib-rn/routers/validateScreenOptions.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/routers/validateScreenOptions'>;
}
declare module 'react-navigation/lib-rn/StateUtils.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/StateUtils'>;
}
declare module 'react-navigation/lib-rn/TypeDefinition.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/TypeDefinition'>;
}
declare module 'react-navigation/lib-rn/views/AnimatedValueSubscription.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/AnimatedValueSubscription'>;
}
declare module 'react-navigation/lib-rn/views/Card.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/Card'>;
}
declare module 'react-navigation/lib-rn/views/CardStack.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/CardStack'>;
}
declare module 'react-navigation/lib-rn/views/CardStackStyleInterpolator.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/CardStackStyleInterpolator'>;
}
declare module 'react-navigation/lib-rn/views/CardStackTransitioner.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/CardStackTransitioner'>;
}
declare module 'react-navigation/lib-rn/views/Drawer/DrawerNavigatorItems.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/Drawer/DrawerNavigatorItems'>;
}
declare module 'react-navigation/lib-rn/views/Drawer/DrawerScreen.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/Drawer/DrawerScreen'>;
}
declare module 'react-navigation/lib-rn/views/Drawer/DrawerSidebar.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/Drawer/DrawerSidebar'>;
}
declare module 'react-navigation/lib-rn/views/Drawer/DrawerView.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/Drawer/DrawerView'>;
}
declare module 'react-navigation/lib-rn/views/Header.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/Header'>;
}
declare module 'react-navigation/lib-rn/views/HeaderBackButton.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/HeaderBackButton'>;
}
declare module 'react-navigation/lib-rn/views/HeaderStyleInterpolator.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/HeaderStyleInterpolator'>;
}
declare module 'react-navigation/lib-rn/views/HeaderTitle.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/HeaderTitle'>;
}
declare module 'react-navigation/lib-rn/views/PointerEventsContainer.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/PointerEventsContainer'>;
}
declare module 'react-navigation/lib-rn/views/ScenesReducer.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/ScenesReducer'>;
}
declare module 'react-navigation/lib-rn/views/SceneView.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/SceneView'>;
}
declare module 'react-navigation/lib-rn/views/TabView/TabBarBottom.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/TabView/TabBarBottom'>;
}
declare module 'react-navigation/lib-rn/views/TabView/TabBarIcon.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/TabView/TabBarIcon'>;
}
declare module 'react-navigation/lib-rn/views/TabView/TabBarTop.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/TabView/TabBarTop'>;
}
declare module 'react-navigation/lib-rn/views/TabView/TabView.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/TabView/TabView'>;
}
declare module 'react-navigation/lib-rn/views/TouchableItem.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/TouchableItem'>;
}
declare module 'react-navigation/lib-rn/views/TransitionConfigs.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/TransitionConfigs'>;
}
declare module 'react-navigation/lib-rn/views/Transitioner.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/Transitioner'>;
}
declare module 'react-navigation/lib-rn/views/withNavigation.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/views/withNavigation'>;
}
declare module 'react-navigation/lib-rn/withCachedChildNavigation.js' {
  declare module.exports: $Exports<'react-navigation/lib-rn/withCachedChildNavigation'>;
}
declare module 'react-navigation/lib/addNavigationHelpers.js' {
  declare module.exports: $Exports<'react-navigation/lib/addNavigationHelpers'>;
}
declare module 'react-navigation/lib/createNavigationContainer.js' {
  declare module.exports: $Exports<'react-navigation/lib/createNavigationContainer'>;
}
declare module 'react-navigation/lib/NavigationActions.js' {
  declare module.exports: $Exports<'react-navigation/lib/NavigationActions'>;
}
declare module 'react-navigation/lib/navigators/createNavigator.js' {
  declare module.exports: $Exports<'react-navigation/lib/navigators/createNavigator'>;
}
declare module 'react-navigation/lib/navigators/DrawerNavigator.js' {
  declare module.exports: $Exports<'react-navigation/lib/navigators/DrawerNavigator'>;
}
declare module 'react-navigation/lib/navigators/NavigatorTypes.js' {
  declare module.exports: $Exports<'react-navigation/lib/navigators/NavigatorTypes'>;
}
declare module 'react-navigation/lib/navigators/StackNavigator.js' {
  declare module.exports: $Exports<'react-navigation/lib/navigators/StackNavigator'>;
}
declare module 'react-navigation/lib/navigators/TabNavigator.js' {
  declare module.exports: $Exports<'react-navigation/lib/navigators/TabNavigator'>;
}
declare module 'react-navigation/lib/PlatformHelpers.js' {
  declare module.exports: $Exports<'react-navigation/lib/PlatformHelpers'>;
}
declare module 'react-navigation/lib/PlatformHelpers.native.js' {
  declare module.exports: $Exports<'react-navigation/lib/PlatformHelpers.native'>;
}
declare module 'react-navigation/lib/react-navigation.js' {
  declare module.exports: $Exports<'react-navigation/lib/react-navigation'>;
}
declare module 'react-navigation/lib/react-navigation.web.js' {
  declare module.exports: $Exports<'react-navigation/lib/react-navigation.web'>;
}
declare module 'react-navigation/lib/routers/createConfigGetter.js' {
  declare module.exports: $Exports<'react-navigation/lib/routers/createConfigGetter'>;
}
declare module 'react-navigation/lib/routers/getScreenConfigDeprecated.js' {
  declare module.exports: $Exports<'react-navigation/lib/routers/getScreenConfigDeprecated'>;
}
declare module 'react-navigation/lib/routers/getScreenForRouteName.js' {
  declare module.exports: $Exports<'react-navigation/lib/routers/getScreenForRouteName'>;
}
declare module 'react-navigation/lib/routers/StackRouter.js' {
  declare module.exports: $Exports<'react-navigation/lib/routers/StackRouter'>;
}
declare module 'react-navigation/lib/routers/TabRouter.js' {
  declare module.exports: $Exports<'react-navigation/lib/routers/TabRouter'>;
}
declare module 'react-navigation/lib/routers/validateRouteConfigMap.js' {
  declare module.exports: $Exports<'react-navigation/lib/routers/validateRouteConfigMap'>;
}
declare module 'react-navigation/lib/routers/validateScreenOptions.js' {
  declare module.exports: $Exports<'react-navigation/lib/routers/validateScreenOptions'>;
}
declare module 'react-navigation/lib/StateUtils.js' {
  declare module.exports: $Exports<'react-navigation/lib/StateUtils'>;
}
declare module 'react-navigation/lib/TypeDefinition.js' {
  declare module.exports: $Exports<'react-navigation/lib/TypeDefinition'>;
}
declare module 'react-navigation/lib/views/AnimatedValueSubscription.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/AnimatedValueSubscription'>;
}
declare module 'react-navigation/lib/views/Card.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/Card'>;
}
declare module 'react-navigation/lib/views/CardStack.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/CardStack'>;
}
declare module 'react-navigation/lib/views/CardStackStyleInterpolator.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/CardStackStyleInterpolator'>;
}
declare module 'react-navigation/lib/views/CardStackTransitioner.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/CardStackTransitioner'>;
}
declare module 'react-navigation/lib/views/Drawer/DrawerNavigatorItems.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/Drawer/DrawerNavigatorItems'>;
}
declare module 'react-navigation/lib/views/Drawer/DrawerScreen.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/Drawer/DrawerScreen'>;
}
declare module 'react-navigation/lib/views/Drawer/DrawerSidebar.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/Drawer/DrawerSidebar'>;
}
declare module 'react-navigation/lib/views/Drawer/DrawerView.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/Drawer/DrawerView'>;
}
declare module 'react-navigation/lib/views/Header.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/Header'>;
}
declare module 'react-navigation/lib/views/HeaderBackButton.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/HeaderBackButton'>;
}
declare module 'react-navigation/lib/views/HeaderStyleInterpolator.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/HeaderStyleInterpolator'>;
}
declare module 'react-navigation/lib/views/HeaderTitle.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/HeaderTitle'>;
}
declare module 'react-navigation/lib/views/PointerEventsContainer.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/PointerEventsContainer'>;
}
declare module 'react-navigation/lib/views/ScenesReducer.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/ScenesReducer'>;
}
declare module 'react-navigation/lib/views/SceneView.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/SceneView'>;
}
declare module 'react-navigation/lib/views/TabView/TabBarBottom.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/TabView/TabBarBottom'>;
}
declare module 'react-navigation/lib/views/TabView/TabBarIcon.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/TabView/TabBarIcon'>;
}
declare module 'react-navigation/lib/views/TabView/TabBarTop.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/TabView/TabBarTop'>;
}
declare module 'react-navigation/lib/views/TabView/TabView.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/TabView/TabView'>;
}
declare module 'react-navigation/lib/views/TouchableItem.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/TouchableItem'>;
}
declare module 'react-navigation/lib/views/TransitionConfigs.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/TransitionConfigs'>;
}
declare module 'react-navigation/lib/views/Transitioner.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/Transitioner'>;
}
declare module 'react-navigation/lib/views/withNavigation.js' {
  declare module.exports: $Exports<'react-navigation/lib/views/withNavigation'>;
}
declare module 'react-navigation/lib/withCachedChildNavigation.js' {
  declare module.exports: $Exports<'react-navigation/lib/withCachedChildNavigation'>;
}
declare module 'react-navigation/src/__tests__/addNavigationHelpers-test.js' {
  declare module.exports: $Exports<'react-navigation/src/__tests__/addNavigationHelpers-test'>;
}
declare module 'react-navigation/src/__tests__/NavigationActions-test.js' {
  declare module.exports: $Exports<'react-navigation/src/__tests__/NavigationActions-test'>;
}
declare module 'react-navigation/src/__tests__/NavigationStateUtils-test.js' {
  declare module.exports: $Exports<'react-navigation/src/__tests__/NavigationStateUtils-test'>;
}
declare module 'react-navigation/src/addNavigationHelpers.js' {
  declare module.exports: $Exports<'react-navigation/src/addNavigationHelpers'>;
}
declare module 'react-navigation/src/createNavigationContainer.js' {
  declare module.exports: $Exports<'react-navigation/src/createNavigationContainer'>;
}
declare module 'react-navigation/src/NavigationActions.js' {
  declare module.exports: $Exports<'react-navigation/src/NavigationActions'>;
}
declare module 'react-navigation/src/navigators/createNavigator.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/createNavigator'>;
}
declare module 'react-navigation/src/navigators/DrawerNavigator.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/DrawerNavigator'>;
}
declare module 'react-navigation/src/navigators/NavigatorTypes.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/NavigatorTypes'>;
}
declare module 'react-navigation/src/navigators/StackNavigator.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/StackNavigator'>;
}
declare module 'react-navigation/src/navigators/TabNavigator.js' {
  declare module.exports: $Exports<'react-navigation/src/navigators/TabNavigator'>;
}
declare module 'react-navigation/src/PlatformHelpers.js' {
  declare module.exports: $Exports<'react-navigation/src/PlatformHelpers'>;
}
declare module 'react-navigation/src/PlatformHelpers.native.js' {
  declare module.exports: $Exports<'react-navigation/src/PlatformHelpers.native'>;
}
declare module 'react-navigation/src/react-navigation.js' {
  declare module.exports: $Exports<'react-navigation/src/react-navigation'>;
}
declare module 'react-navigation/src/react-navigation.web.js' {
  declare module.exports: $Exports<'react-navigation/src/react-navigation.web'>;
}
declare module 'react-navigation/src/routers/__tests__/createConfigGetter-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/createConfigGetter-test'>;
}
declare module 'react-navigation/src/routers/__tests__/Routers-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/Routers-test'>;
}
declare module 'react-navigation/src/routers/__tests__/StackRouter-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/StackRouter-test'>;
}
declare module 'react-navigation/src/routers/__tests__/TabRouter-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/TabRouter-test'>;
}
declare module 'react-navigation/src/routers/__tests__/validateRouteConfigMap-test.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/__tests__/validateRouteConfigMap-test'>;
}
declare module 'react-navigation/src/routers/createConfigGetter.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/createConfigGetter'>;
}
declare module 'react-navigation/src/routers/getScreenConfigDeprecated.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/getScreenConfigDeprecated'>;
}
declare module 'react-navigation/src/routers/getScreenForRouteName.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/getScreenForRouteName'>;
}
declare module 'react-navigation/src/routers/StackRouter.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/StackRouter'>;
}
declare module 'react-navigation/src/routers/TabRouter.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/TabRouter'>;
}
declare module 'react-navigation/src/routers/validateRouteConfigMap.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/validateRouteConfigMap'>;
}
declare module 'react-navigation/src/routers/validateScreenOptions.js' {
  declare module.exports: $Exports<'react-navigation/src/routers/validateScreenOptions'>;
}
declare module 'react-navigation/src/StateUtils.js' {
  declare module.exports: $Exports<'react-navigation/src/StateUtils'>;
}
declare module 'react-navigation/src/TypeDefinition.js' {
  declare module.exports: $Exports<'react-navigation/src/TypeDefinition'>;
}
declare module 'react-navigation/src/views/__tests__/NavigationScenesReducer-test.js' {
  declare module.exports: $Exports<'react-navigation/src/views/__tests__/NavigationScenesReducer-test'>;
}
declare module 'react-navigation/src/views/AnimatedValueSubscription.js' {
  declare module.exports: $Exports<'react-navigation/src/views/AnimatedValueSubscription'>;
}
declare module 'react-navigation/src/views/Card.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Card'>;
}
declare module 'react-navigation/src/views/CardStack.js' {
  declare module.exports: $Exports<'react-navigation/src/views/CardStack'>;
}
declare module 'react-navigation/src/views/CardStackStyleInterpolator.js' {
  declare module.exports: $Exports<'react-navigation/src/views/CardStackStyleInterpolator'>;
}
declare module 'react-navigation/src/views/CardStackTransitioner.js' {
  declare module.exports: $Exports<'react-navigation/src/views/CardStackTransitioner'>;
}
declare module 'react-navigation/src/views/Drawer/DrawerNavigatorItems.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Drawer/DrawerNavigatorItems'>;
}
declare module 'react-navigation/src/views/Drawer/DrawerScreen.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Drawer/DrawerScreen'>;
}
declare module 'react-navigation/src/views/Drawer/DrawerSidebar.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Drawer/DrawerSidebar'>;
}
declare module 'react-navigation/src/views/Drawer/DrawerView.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Drawer/DrawerView'>;
}
declare module 'react-navigation/src/views/Header.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Header'>;
}
declare module 'react-navigation/src/views/HeaderBackButton.js' {
  declare module.exports: $Exports<'react-navigation/src/views/HeaderBackButton'>;
}
declare module 'react-navigation/src/views/HeaderStyleInterpolator.js' {
  declare module.exports: $Exports<'react-navigation/src/views/HeaderStyleInterpolator'>;
}
declare module 'react-navigation/src/views/HeaderTitle.js' {
  declare module.exports: $Exports<'react-navigation/src/views/HeaderTitle'>;
}
declare module 'react-navigation/src/views/PointerEventsContainer.js' {
  declare module.exports: $Exports<'react-navigation/src/views/PointerEventsContainer'>;
}
declare module 'react-navigation/src/views/ScenesReducer.js' {
  declare module.exports: $Exports<'react-navigation/src/views/ScenesReducer'>;
}
declare module 'react-navigation/src/views/SceneView.js' {
  declare module.exports: $Exports<'react-navigation/src/views/SceneView'>;
}
declare module 'react-navigation/src/views/TabView/TabBarBottom.js' {
  declare module.exports: $Exports<'react-navigation/src/views/TabView/TabBarBottom'>;
}
declare module 'react-navigation/src/views/TabView/TabBarIcon.js' {
  declare module.exports: $Exports<'react-navigation/src/views/TabView/TabBarIcon'>;
}
declare module 'react-navigation/src/views/TabView/TabBarTop.js' {
  declare module.exports: $Exports<'react-navigation/src/views/TabView/TabBarTop'>;
}
declare module 'react-navigation/src/views/TabView/TabView.js' {
  declare module.exports: $Exports<'react-navigation/src/views/TabView/TabView'>;
}
declare module 'react-navigation/src/views/TouchableItem.js' {
  declare module.exports: $Exports<'react-navigation/src/views/TouchableItem'>;
}
declare module 'react-navigation/src/views/TransitionConfigs.js' {
  declare module.exports: $Exports<'react-navigation/src/views/TransitionConfigs'>;
}
declare module 'react-navigation/src/views/Transitioner.js' {
  declare module.exports: $Exports<'react-navigation/src/views/Transitioner'>;
}
declare module 'react-navigation/src/views/withNavigation.js' {
  declare module.exports: $Exports<'react-navigation/src/views/withNavigation'>;
}
declare module 'react-navigation/src/withCachedChildNavigation.js' {
  declare module.exports: $Exports<'react-navigation/src/withCachedChildNavigation'>;
}
